app_two/urls.py
from django.urls import path
from app_two import views

#Template tagging
app_name = "app_two"

urlpatterns = [
    # path(r'^$',views.index, name="index"),
    # path(r'^admin/', admin.site.urls),

    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('users', views.users, name='users'),
    path('form_page', views.form_name_view, name='form_name'),
    path('input_user', views.input_user_view, name='input_user'),
    path('other', views.other, name='other'),
    path('relative_urls', views.relative_urls, name='relative_urls'),
    path('user_login', views.user_login, name='user_login'),

]

project_two/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from app_two import views

urlpatterns = [
    path('', views.index, name='index'),
    path('app_two/', include('app_two.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name = 'logout'),
    path('special/', views.special, name = 'special'),
]

app_two/models.py
from django.db import models
from django.contrib.auth.models import User

# # Create your models here.
# class Topic(models.Model):
#     top_name = models.CharField(max_length=264,unique=True)
#
#     def __str__(self):
#         return self.top_name
#
# class Webpage(models.Model):
#     topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
#     name = models.CharField(max_length=264,unique=True)
#     url = models.URLField(unique=True)
#
#     def __str__(self):
#         return self.name
#
# class AccessRecord(models.Model):
#     name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
#     date = models.DateField()
#
#     def __str__(self):
#         return str(self.date)
#
# # class User(models.Model):
# #     first_name = models.CharField(max_length=264)
# #     last_name = models.CharField(max_length=264)
# #     email = models.EmailField(unique=True)
# #
# #     def __str__(self):
# #         return self.first_name


class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

app_two/forms.py
from django import forms
from django.core import validators
# from app_two.models import User
from django.contrib.auth.models import User
from app_two.models import UserProfileInfo



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')


# class InputUser(forms.ModelForm):
#     # first_name = forms.CharField(max_length=264)
#     # last_name = forms.CharField(max_length=264)
#     # email = forms.EmailField(label = "Email")
#     class Meta:
#         model = User
#         fields = "__all__"
#
# def check_for_a(value):
#     if value[0] != "a":
#         raise forms.ValidationError("your name shuld start from A!")
#
# class FormName(forms.Form):
#     name = forms.CharField(validators = [check_for_a])
#     email = forms.EmailField()
#     verify_email = forms.EmailField(label='Enter your email again:')
#     text = forms.CharField(widget=forms.Textarea)
#     botcatcher = forms.CharField(required=False, widget = forms.HiddenInput,
#             validators =[validators.MaxLengthValidator(0)] ) #testing for bot
#     #botcatcher = forms.CharField(required=False, widget = forms.HiddenInput)
#
#     # def clean_botcacher(self):
#     #     botcatcher = self.cleaned_data['botcatcher']
#     #     if len(botcatcher) > 0:
#     #         raise forms.ValidationError("GOTCHA BOT!")
#     #     return botcatcher
#
#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verify_email']
#
#         if email != vmail:
#             raise forms.ValidationError("MAKE SURE EMAILS MATCH!")

app_two/views.py
from django.shortcuts import render, redirect
# from app_two.models import Topic,Webpage,AccessRecord, User
#from . import forms
from app_two.forms import UserForm,UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context_dict = {"text":"hello world", "number":100}
    return render(request, "app_two/index.html", context = context_dict)

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'app_two/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def other(request):
    return render(request, "app_two/other.html")

def relative_urls(request):
    return render(request, "app_two/relative_urls.html")


def users(request):
    all_users = User.objects.all()
    user_dict = {"users": all_users}
    return render(request, "app_two/users.html", context = user_dict)

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            # DO SOMETHING CODE
            print("VALIDATION SUCCESS!")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: "+form.cleaned_data['email'])
            print("TEXT: "+form.cleaned_data['text'])

    return render(request,'app_two/form_page.html',{'form':form})

def input_user_view(request):
    form = forms.InputUser()
    if request.method == 'POST':
        form = forms.InputUser(request.POST)

        if form.is_valid():
            form.save()
            return redirect('users')

    return render(request,'app_two/input_user.html',{'form':form})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')#From the form in html.
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'app_two/login.html', {})

templates/app_two/base.html
<!DOCTYPE html>
{% load %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'app_two:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'app_two:register' %}">Rigister</a></li>

          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'special' %}">Special</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'app_two:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">



    {% block body_block %}
    <!-- {# Anything outside of this will be inherited if you use extend.#} -->
    {% endblock %}
    </div>


  </body>
</html>

templates/app_two/form_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <h1>Fill out the form!</h1>
    <div class="container">
      <form method="POST">
          {{form.as_p}}
          {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>


    </div>

  </body>
</html>

templates/app_two/help.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django guitar page</title>
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
  </head>
  <body>
    <h1>This is Django page</h1>
    {{help_message}}
    <img src="{% static 'images/django.jpeg' %}" alt="Oh-oh">
  </body>
</html>

templates/app_two/index.html
<!DOCTYPE html>

{% extends "app_two/base.html" %}
    {% block body_block %}

    <div class="jumbotron">
      <h1>Django level five</h1>
    </div>

    {% endblock %}

templates/app_two/input_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <h1>Provide your personal data!</h1>
    <div class="container">
      <form method="POST">
          {{form.as_p}}
          {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>


    </div>

  </body>
</html>

templates/app_two/login.html
{% extends 'app_two/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'app_two:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/app_two/other.html
<!DOCTYPE html>
{% extends "app_two/base.html" %}
    {% block body_block %}
    <h1>This is an example of template inheritance!</h1>
    <h2>Officially this is the other.html page!</h2>
    {% endblock %}

templates/app_two/registration.html
{% extends "app_two/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

templates/app_two/relative_urls.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative!</h1>
    <a href="{% url 'app_two:other' %}">Other </a>
    <a href="{% url 'admin:index' %}">To admin page</a>
    <a href="{% url 'app_two:index' %}">To INDEX page</a>
  </body>
</html>

templates/app_two/temp.html
<ol>
  <li>First ordered list item</li>
  <li>Second ordered list item</li>
  <li>Third ordered list item</li>
  <ul>
    <li>Unordered list item 1</li>
    <li>Unordered list item 2</li>
    <li>Unordered list item 3</li>
  </ul>
  <li>Fourth ordered list item</li>
</ol>

templates/app_two/users.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}"/>
  </head>
  <body>
    <h1>Hi, below are the fake users</h1>
    <div class="djangtwo">

      {% if users %}
        <ol>
          {% for user in users %}
              <li>User info:</li>
              <ul>
                <li>First Name: {{user.first_name}}</li>
                <li>Last Name: {{user.last_name}}</li>
                <li>Email: {{user.email}}</li>
              </ul>

            {% endfor %}
        </ol>

      {% else %}
        <p>No Access Records. Table Not Created.</p>
      {% endif %}
    </div>


  </body>
</html>